export const armies = [
  // Adepta Sororitas
  {
    name: "Adepta Sororitas",
    squads: [
      {
        name: "Battle Sisters Squad",
        min: 5,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "1 x Simulacrum Imperialis",
          "1 x Incensor Cherub",
          "1 x Simulacrum Imperialis and Incensor Cherub",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [
          "Artificier-crafted Storm Bolter (1 model)",
          "Meltagun (1 model)",
          "Ministorum Flamer (1 model)",
        ],
        heavyWeapons: [
          "Heavy Bolter (1 model)",
          "Ministorum Heavy Flamer (1 model)",
          "Multi-melta (1 model)",
        ],
        hasLeader: true,
        leader: {
          name: "Sister Superior",
          leaderWeapon1: [
            "Bolt Pistol",
            "Inferno Pistol",
            "Ministorum Hand Flamer",
            "Plasma Pistol",
            "Boltgun",
            "Combi-melta",
            "Combi-plasma",
            "Condemnor Boltgun",
            "Ministorum Combi-flamer",
          ],
          leaderWeapon2: ["Chainsword", "Power Maul", "Power Sword"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Sisters Novitiate",
        min: 10,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "1 x Simulacrum Imperialis",
          "1 x Sacred Banner",
          "1 x Simulacrum Imperialis and Sacred Banner",
        ],
        restrictSpecialAndHeavy: false,
        specialWeapons: ["Ministorum Flamer (max 2 models) "],
        heavyWeapons: ["Novitiate Melee Weapons (any number of models)"],
        hasLeader: true,
        leader: {
          name: "Novitiate Superior",
          leaderWeapon1: ["Bolt Pistol", "Plasma Pistol"],
          leaderWeapon2: ["Power Sword"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // Adeptus Custodes
  {
    name: "Adeptus Custodes",
    squads: [
      {
        name: "Custodian Guard",
        min: 3,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Sentinel Blade and Praesidium Shield",
          "Sentinel Blade and Misericordia",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
      {
        name: "Custodian Guard with Adrasite and Pyrithite Spears",
        min: 3,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Adrasite Spear",
          "Adrasite Spear and Misericordia",
          "Pyrithite Spear",
          "Pyrithite Spear and Misericordia",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
      {
        name: "Allarus Custodians",
        min: 1,
        max: 6,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Guardian Spear",
          "Guardian Spear and Misericordia",
          "Castellan Axe",
          "Castellan Axe and Misericordia",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
      {
        name: "Sagittarum Custodian",
        min: 3,
        max: 5,
        optionalSquadEquipment: ["Misericordia"],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
      {
        name: "Prosecutor",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Prosecutor Sister Superior",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // Adeptus Custodes
  {
    name: "Adeptus Mechanicus",
    squads: [
      {
        name: "Skitarii Rangers",
        min: 5,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "1 x Enhanced Data-tether (1 every 10 models)",
          "1 x Omnispex (1 every 10 models)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [
          "Arc Rifle (1 every 10 models)",
          "Plasma Caliver (1 every 10 models)",
          "Transuranic Arquebus (1 every 10 models)",
        ],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Skitarii Ranger Alpha",
          leaderWeapon1: [
            "Galvanic Rifle",
            "Arc Pistol",
            "Phosphor Blast Pistol",
            "Radium Pistol",
          ],
          leaderWeapon2: ["Arc Maul", "Power Sword", "Taser Goad"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Skitarii Vanguard",
        min: 5,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "1 x Enhanced Data-tether (1 every 10 models)",
          "1 x Omnispex (1 every 10 models)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [
          "Arc Rifle (1 every 10 models)",
          "Plasma Caliver (1 every 10 models)",
          "Transuranic Arquebus (1 every 10 models)",
        ],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Skitarii Ranger Alpha",
          leaderWeapon1: [
            "Radium Carbine",
            "Arc Pistol",
            "Phosphor Blast Pistol",
            "Radium Pistol",
          ],
          leaderWeapon2: ["Arc Maul", "Power Sword", "Taser Goad"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Ironstride Ballistarii",
        min: 1,
        max: 6,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Twin Cognis Autocannon (any number of models)",
          "Twin Cognis Lascannon (any number of models)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Skitarii Ranger Alpha",
          leaderWeapon1: [
            "Radium Carbine",
            "Arc Pistol",
            "Phosphor Blast Pistol",
            "Radium Pistol",
          ],
          leaderWeapon2: ["Arc Maul", "Power Sword", "Taser Goad"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Serberys Sulphurhounds",
        min: 3,
        max: 9,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "2 x Phosphor Pistols (every model)",
          "Phosphor Blast Carbine and Phosphor Pistol (1 every 3 models)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Serberys Sulphurhound Alpha",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Serberys Raiders",
        min: 3,
        max: 9,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: ["1 x Enhanched Data-tether (1 model)"],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Serberys Sulphurhound Alpha",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Pteraxii Skystalkers",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Serberys Sulphurhound Alpha",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Pteraxii Sterylizors",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Serberys Sulphurhound Alpha",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // Aeldari
  {
    name: "Aeldari (Eldar)",
    squads: [
      {
        name: "Guardian Defenders",
        min: 10,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Heavy Weapon Platform x1",
          "Heavy Weapon Platform x2",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
    ],
  },
  // Imperial Guard
  {
    name: "Astra Militarum (Imperial Guard)",
    squads: [
      {
        name: "Infantry Squad (Guardsmen)",
        min: 10,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: ["Voxcaster"],
        restrictSpecialAndHeavy: false,
        specialWeapons: [
          "Sniper Rifle (1 model)",
          "Flamer (1 model)",
          "Grenade Launcher (1 model)",
          "Meltagun (1 model)",
          "Plasma Gun (1 model)",
          "Breacher Charge (1 model)",
          "Lascutter (1 model)",
        ],
        heavyWeapons: [
          "Mortar (2 models team)",
          "Autocannon (2 models team)",
          "Heavy Bolter (2 models team)",
          "Missile Launcher (2 models team)",
          "Lascannon (2 models team)",
        ],
        hasLeader: true,
        leader: {
          name: "Sergeant",
          leaderWeapon1: [
            "Laspistol",
            "Bolt Pistol",
            "Boltgun",
            "Plasma Pistol",
          ],
          leaderWeapon2: ["Chainsword", "Power Sword"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Infantry Squad (Conscripts)",
        min: 20,
        max: 30,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
    ],
  },
  // Chaos Daemons
  {
    name: "Chaos Daemons",
    squads: [
      {
        name: "Bloodletters of Khorne",
        min: 10,
        max: 30,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Instrument of Chaos (1 every 10 models)",
          "Daemonic Icon (1 every 10 models)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Bloodreaper",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // Drukhari
  {
    name: "Drukhari (Dark Eldar)",
    squads: [
      {
        name: "Kabalite Warriors",
        min: 5,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: false,
        specialWeapons: [
          "Blaster (1 every 5 models)",
          "Shredder (1 every 5 models)",
        ],
        heavyWeapons: [
          "Dark lance (1 every 10 models)",
          "Splinter cannon (1 every 10 models)",
        ],
        hasLeader: true,
        leader: {
          name: "Sybarite",
          leaderWeapon1: ["Power Sword", "Agoniser"],
          leaderWeapon2: ["Splinter Rifle", "Splinter Pistol", "Blast Pistol"],
          restrictOptionalEquipment: false,
          leaderOptionalEquipment: ["Phantasm Grenade Launcher"],
        },
      },
    ],
  },
  // Chaos Space Marines
  {
    name: "Chaos Space Marines",
    squads: [
      {
        name: "Chaos Space Marines",
        min: 5,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "1 x Icon of Wrath",
          "1 x Icon of Flame",
          "1 x Icon of Despair",
          "1 x Icon of Excess",
          "1 x Icon of Leadership",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: ["Flamer", "Meltagun", "Plasma Gun"],
        heavyWeapons: [
          "Autocannon",
          "Heavy Bolter",
          "Lascannon",
          "Missile Launcher",
          "Reaper Chaincannon",
        ],
        hasLeader: true,
        leader: {
          name: "Aspiring Champion",
          leaderWeapon1: [
            "Bolt Pistol",
            "Chainaxe",
            "Chainsword",
            "Lightning Claw",
            "Plasma Pistol",
            "Boltgun",
            "Combi-bolter",
            "Combi-flamer",
            "Combi-melta",
            "Combi-melta",
            "Combi-plasma",
          ],
          leaderWeapon2: [
            "Power Axe",
            "Power Fist",
            "Power Maul",
            "Power Sword",
          ],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Chaos Cultists",
        min: 10,
        max: 30,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Heavy Stubber (1 every 10 models)",
          "Flamer (1 every 10 models)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        leader: {
          name: "Aspiring Champion",
          leaderWeapon1: ["Autogun"],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [
            "Shotgun",
            "Autopist and Brutal Assault Weapon",
          ],
        },
      },
      {
        name: "Raptors",
        min: 5,
        max: 15,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: ["1 x Chaos Icon"],
        restrictSpecialAndHeavy: true,
        specialWeapons: [
          "Plasma Pistol and Chainsword (2 models)",
          "Flamer (2 models)",
          "Meltagun (2 models)",
          "Plasma Gun (2 models)",
        ],
        heavyWeapons: [],
        leader: {
          name: "Aspiring Champion",
          leaderWeapon1: [
            "Bolt Pistol",
            "Chainaxe",
            "Chainsword",
            "Ligthning Claw",
            "Plasma Pistol",
            "Power Axe",
            "Power Fist",
            "Power Maul",
            "Power Sword",
          ],
          leaderWeapon2: [
            "Boltgun",
            "Combi-bolter",
            "Combi-flamer",
            "Combi-melta",
            "Combi-plasma",
          ],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [
            "Shotgun",
            "Autopist and Brutal Assault Weapon",
          ],
        },
      },
    ],
  },
  // Genestealer Cults
  {
    name: "Genestealer Cults",
    squads: [
      {
        name: "Acolyte Hybrids",
        min: 5,
        max: 15,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: ["1 x Cult Icon"],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Acolyte Leader",
          leaderWeapon1: ["Autopistol", "Cult Bonesword", "Cult Lash Whip"],
          leaderWeapon2: ["Cult Claws and Knife"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // Necrons
  {
    name: "Necrons",
    squads: [
      {
        name: "Necron Warriors",
        min: 10,
        max: 20,
        alternativeSquadBasicLoadout: ["Gauss Reapers (any number of models)"],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
    ],
  },
  //   Orks
  {
    name: "Orks",
    squads: [
      {
        name: "Ork Boyz",
        min: 10,
        max: 30,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Boss Nob",
          leaderWeapon1: [
            "Big Chooppa",
            "Choppa",
            "Killsaw",
            "Power Klaw",
            "Power Stabba",
            "Slugga",
          ],
          leaderWeapon2: [
            "Big Chooppa",
            "Choppa",
            "Killsaw",
            "Power Klaw",
            "Power Stabba",
            "Slugga",
          ],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: ["Kombi-rokkit", "Kombi-skorcha"],
        },
      },
      {
        name: "Stormboyz",
        min: 5,
        max: 15,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Boss Nob",
          leaderWeapon1: ["Slugga"],
          leaderWeapon2: ["Choppa", "Power Klaw"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // T'au
  {
    name: "T'au",
    squads: [
      {
        name: "Kroot Carnivores",
        min: 10,
        max: 20,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
      {
        name: "Pathfinder Team",
        min: 10,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [
          "Semi-automatic Grenade Launcher (1 model)",
          "Neuroweb System Jammer (1 model)",
          "Drone Controller (1 model)",
        ],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: ["Ion Rifle (max 3 models)", "Rail Rifle (max 3 models)"],
        hasLeader: true,
        leader: {
          name: "Pathfinder Shas'ui",
          leaderWeapon1: [],
          leaderWeapon2: [],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
  // Tyranids
  {
    name: "Tyranids",
    squads: [
      {
        name: "Termagants",
        min: 10,
        max: 30,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [],
        hasLeader: false,
        leader: {},
      },
    ],
  },

  // Space Marines
  {
    name: "Space Marines",
    squads: [
      {
        name: "Intercessor Squad",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [
          "Auto Bolt Rifles (any number of  models)",
          "Stalker Bolt Rifles (any number of models models)",
        ],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: ["Grenade Launcher (1 every 5 models)"],
        heavyWeapons: [],
        hasLeader: true,
        leader: {
          name: "Intercessor Sergeant",
          leaderWeapon1: [
            "Bolt Rifle",
            "Auto Bolt Rifle",
            "Stalker Bolt Rifle",
            "Hand Flamer",
            "Plasma Pistol",
          ],
          leaderWeapon2: [
            "Chainsword",
            "Power Fist",
            "Power Sword",
            "Thunderhammer",
          ],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Tactical Squad",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: [],
        restrictSpecialAndHeavy: true,
        specialWeapons: [
          "Flamer (1 model)",
          "Grav-gun (1 model)",
          "Meltagun (1 model)",
          "Plasma gun (1 model)",
        ],
        heavyWeapons: [
          "Grav-cannon (1 model)",
          "Heavy Bolter (1 model)",
          "Heavy Flamer (1 model)",
          "Lascannon (1 model)",
          "Missile Launcher (1 model)",
          "Multi-melta (1 model)",
          "Plasma Cannon (1 model)",
        ],
        hasLeader: true,
        leader: {
          name: "Space Marine Sergeant",
          leaderWeapon1: [
            "Bolt Pistol",
            "Hand Flamer",
            "Grav Pistol",
            "Inferno Pistol",
            "Plasma Pistol",
            "Combi-flamer",
            "Combi-grav",
            "Combi-melta",
            "Combi-plasma",
            "Storm Bolter",
          ],
          leaderWeapon2: [
            "Chainsword",
            "Lightning Claw",
            "Power Axe",
            "Power Fist",
            "Power Maul",
            "Power Sword",
            "Thunderhammer",
          ],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
      {
        name: "Assault Squad",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: ["Jump Packs"],
        restrictSpecialAndHeavy: false,
        specialWeapons: [
          "Plasma Pistol and Chainsword (2 models)",
          "Flamer (2 models)",
          "Meltagun (2 models)",
          "Plasma Gun (2 models)",
        ],
        heavyWeapons: ["Eviscerator (1 every 5 models)"],
        hasLeader: true,
        leader: {
          name: "Assault Marine Sergeant",
          leaderWeapon1: [
            "Bolt Pistol",
            "Hand Flamer",
            "Grav Pistol",
            "Inferno Pistol",
            "Plasma Pistol",
          ],
          leaderWeapon2: [
            "Chainsword",
            "Lightning Claw",
            "Power Axe",
            "Power Fist",
            "Power Maul",
            "Power Sword",
            "Thunderhammer",
          ],
          restrictOptionalEquipment: false,
          leaderOptionalEquipment: ["Combat Shield"],
        },
      },
      {
        name: "Terminator Squad",
        min: 5,
        max: 10,
        alternativeSquadBasicLoadout: [],
        optionalSquadEquipment: ["1 x Teleport homer"],
        restrictSpecialAndHeavy: true,
        specialWeapons: [],
        heavyWeapons: [
          "Assault Cannon (1 every 5 models)",
          "Heavy Flamer (1 every 5 models)",
          "Storm Bolter and Cyclone Missile Launcher (1 every 5 models)",
        ],
        hasLeader: true,
        leader: {
          name: "Terminator Sergeant",
          leaderWeapon1: ["Storm Bolter"],
          leaderWeapon2: ["Power Sword"],
          restrictOptionalEquipment: true,
          leaderOptionalEquipment: [],
        },
      },
    ],
  },
];
